# Generated by Django 3.2.5 on 2021-12-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone_No', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=200)),
                ('Subject', models.CharField(max_length=400)),
                ('Message', models.TextField()),
                ('Proposal', models.FileField(upload_to='uploads/%Y/%m/%d')),
            ],
        ),
    ]
